apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
