apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: deployment_patch.yaml
nameSuffix: -prod
labels:
  - includeSelectors: true
    pairs:
      variant: prod
secretGenerator:
  - name: nginx-secret
    type: Opaque
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
