apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: nginx
          image: nginx:stable
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Australia/Perth"
